name: "CI - Test Features"
on:
  push:
    branches:
      - main
    paths:
      - src/**/devcontainer-feature.json
      - src/**/NOTE.md
      - .github/workflows/update-readme.yaml
  pull_request:
    paths:
      - src/**/devcontainer-feature.json
      - src/**/NOTE.md
      - .github/workflows/update-readme.yaml
  workflow_dispatch:

jobs:
  update-readme:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: "Update readme for features"
        uses: devcontainers/action@v1
        with:
          base-path-to-features: "./src"
          generate-docs: "true"

      - uses: devcontainers-community/update-collection-readme@v1

      - uses: stefanzweifel/git-auto-commit-action@v4