name: "Validate devcontainer-feature.json files"
on:
  push:
    branches:
      - main
    paths:
      - src/**/devcontainer-feature.json
      - .github/workflows/validate.yaml
  pull_request:
  workflow_dispatch:

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: "Validate devcontainer-feature.json files"
        uses: devcontainers/action@v1
        with:
          validate-only: "true"
          base-path-to-features: "./src"
